services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    container_name: obsidian-db
