import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatePlantV21741135270845 implements MigrationInterface {
    name = 'UpdatePlantV21741135270845'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cleaning_container" RENAME COLUMN "agentCleaning" TO "agent_cleaning"`);
        await queryRunner.query(`ALTER TABLE "disinfection_container" RENAME COLUMN "agentDisinfection" TO "agent_disinfection"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" DROP COLUMN "dateOfStorage"`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" DROP COLUMN "quantityEnter"`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" DROP COLUMN "quantityOut"`);
        await queryRunner.query(`ALTER TABLE "control_product" DROP COLUMN "batchNum"`);
        await queryRunner.query(`ALTER TABLE "control_product" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "control_product" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" DROP COLUMN "operationCarriedOut"`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" DROP COLUMN "operationCarriedOut"`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ceiling" DROP COLUMN "entrustedReview"`);
        await queryRunner.query(`ALTER TABLE "ceiling" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ceiling" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "walls" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "walls" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP COLUMN "entrustedReview"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "openings" DROP COLUMN "entrustedReview"`);
        await queryRunner.query(`ALTER TABLE "openings" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "openings" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" DROP COLUMN "entrustedReview"`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "plant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "plant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "batchNum"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "numDomain"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" DROP COLUMN "numDomain"`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "created_at" date NOT NULL DEFAULT '2025-03-05T00:41:12.798Z'`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updated_at" date NOT NULL DEFAULT '2025-03-05T00:41:12.798Z'`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" ADD "date_of_storage" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.135Z'`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.135Z'`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" ADD "quantity_enter" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" ADD "quantity_out" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_product" ADD "batch_num" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_product" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.147Z'`);
        await queryRunner.query(`ALTER TABLE "control_product" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.147Z'`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" ADD "operation_carried_out" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.153Z'`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.153Z'`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" ADD "operation_carried_out" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.162Z'`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.162Z'`);
        await queryRunner.query(`ALTER TABLE "ceiling" ADD "entrusted_review" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ceiling" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.184Z'`);
        await queryRunner.query(`ALTER TABLE "ceiling" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.184Z'`);
        await queryRunner.query(`ALTER TABLE "walls" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.190Z'`);
        await queryRunner.query(`ALTER TABLE "walls" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.190Z'`);
        await queryRunner.query(`ALTER TABLE "floor" ADD "entrusted_review" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "floor" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.197Z'`);
        await queryRunner.query(`ALTER TABLE "floor" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.197Z'`);
        await queryRunner.query(`ALTER TABLE "openings" ADD "entrusted_review" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "openings" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.203Z'`);
        await queryRunner.query(`ALTER TABLE "openings" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.203Z'`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" ADD "entrusted_review" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "plant" ADD "created_at" date NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "plant" ADD "updated_at" date NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "batch_num" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "num_domain" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" ADD "num_domain" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" ADD "created_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" ADD "updated_at" text NOT NULL DEFAULT '2025-03-05T00:41:13.209Z'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" DROP COLUMN "num_domain"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "num_domain"`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" DROP COLUMN "batch_num"`);
        await queryRunner.query(`ALTER TABLE "plant" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "plant" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" DROP COLUMN "entrusted_review"`);
        await queryRunner.query(`ALTER TABLE "openings" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "openings" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "openings" DROP COLUMN "entrusted_review"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP COLUMN "entrusted_review"`);
        await queryRunner.query(`ALTER TABLE "walls" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "walls" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "ceiling" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "ceiling" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "ceiling" DROP COLUMN "entrusted_review"`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" DROP COLUMN "operation_carried_out"`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" DROP COLUMN "operation_carried_out"`);
        await queryRunner.query(`ALTER TABLE "control_product" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "control_product" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "control_product" DROP COLUMN "batch_num"`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" DROP COLUMN "quantity_out"`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" DROP COLUMN "quantity_enter"`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" DROP COLUMN "date_of_storage"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.656Z'`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.656Z'`);
        await queryRunner.query(`ALTER TABLE "vehicle_transfer" ADD "numDomain" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.657Z'`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.657Z'`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "numDomain" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_dispatch" ADD "batchNum" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "plant" ADD "updatedAt" date NOT NULL DEFAULT '2025-03-05'`);
        await queryRunner.query(`ALTER TABLE "plant" ADD "createdAt" date NOT NULL DEFAULT '2025-03-05'`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.668Z'`);
        await queryRunner.query(`ALTER TABLE "cleaning_disinfection_area_working" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.668Z'`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.668Z'`);
        await queryRunner.query(`ALTER TABLE "structure_hardware_utensils" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.668Z'`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.596Z'`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.596Z'`);
        await queryRunner.query(`ALTER TABLE "shelves_pallets" ADD "entrustedReview" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "openings" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.590Z'`);
        await queryRunner.query(`ALTER TABLE "openings" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.590Z'`);
        await queryRunner.query(`ALTER TABLE "openings" ADD "entrustedReview" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "floor" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.583Z'`);
        await queryRunner.query(`ALTER TABLE "floor" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.583Z'`);
        await queryRunner.query(`ALTER TABLE "floor" ADD "entrustedReview" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "walls" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.668Z'`);
        await queryRunner.query(`ALTER TABLE "walls" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.668Z'`);
        await queryRunner.query(`ALTER TABLE "ceiling" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.576Z'`);
        await queryRunner.query(`ALTER TABLE "ceiling" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.576Z'`);
        await queryRunner.query(`ALTER TABLE "ceiling" ADD "entrustedReview" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.667Z'`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.667Z'`);
        await queryRunner.query(`ALTER TABLE "control_pre_operational" ADD "operationCarriedOut" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.662Z'`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.662Z'`);
        await queryRunner.query(`ALTER TABLE "control_post_operational" ADD "operationCarriedOut" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "control_product" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.641Z'`);
        await queryRunner.query(`ALTER TABLE "control_product" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.641Z'`);
        await queryRunner.query(`ALTER TABLE "control_product" ADD "batchNum" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" ADD "quantityOut" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drums_quantity" ADD "quantityEnter" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" ADD "dateOfStorage" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" ADD "updatedAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.632Z'`);
        await queryRunner.query(`ALTER TABLE "equipment_container_sanitation" ADD "createdAt" text NOT NULL DEFAULT '2025-03-05T00:12:29.632Z'`);
        await queryRunner.query(`ALTER TABLE "user" ADD "updatedAt" date NOT NULL DEFAULT '2025-03-05'`);
        await queryRunner.query(`ALTER TABLE "user" ADD "createdAt" date NOT NULL DEFAULT '2025-03-05'`);
        await queryRunner.query(`ALTER TABLE "disinfection_container" RENAME COLUMN "agent_disinfection" TO "agentDisinfection"`);
        await queryRunner.query(`ALTER TABLE "cleaning_container" RENAME COLUMN "agent_cleaning" TO "agentCleaning"`);
    }

}
